# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "Development" ]


jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.19.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.19.0
        cache: 'npm'
    - run: npm ci
    - run: cp -r ./* /home/centos/snapebackend/
    - run: sudo pm2 restart snape-client-apis
